name: barbershop

on:
  pull_request:
    branches:
      - master
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checks-out
        uses: actions/checkout@v3

      - name: Lint
        run: npx next lint

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build
