name: barbershop

on:
  pull_request:
    branches:
      - main
      - development
      - release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checks-out
        uses: actions/checkout@v3

      - name: Install modules
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test

      # - name: Build
      #   run: npm run build
